import { ethers } from "ethers"
import Web3Modal from "web3modal"
import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import { Result } from 'postcss'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import styles from '../styles/Home.module.css'
import requests from "../utils/requests"

export default function Home() {
  const [user, setUser] = useState({})

  async function connectUser() {
    const web3Modal = new Web3Modal()
    const connection = await web3Modal.connect()
    const provider = new ethers.providers.Web3Provider(connection)
    const signer = provider.getSigner()
    
    const connectedUser = {
      provider: provider,
      signer: signer,
      signerAddress: signer.getAddress(),
    }
    setUser(connectedUser)
  }
 
  return (
    <div>
      <Head>
        <title>ULoan</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* Header */}
      <Header> 
        
      </Header>
    {/* Nav */}
    
      <Nav />
  
    {/* Results */}
     <Results />
    </div>
  )
  // export async function getServerSideProps(context) {
  //   const genre = context.query.genre;
  // }
}
